FROM lscr.io/linuxserver/code-server:latest

RUN apt-get update && \
    apt-get install -y \
        openjdk-21-jdk \
        maven \
        gradle \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

ENV JAVA_HOME=/usr/lib/jvm/java-21-openjdk-amd64
ENV PATH="$JAVA_HOME/bin:$PATH"

RUN java -version && javac -version && mvn -version && gradle -version
