FROM lscr.io/linuxserver/code-server:latest


RUN apt-get update && \
    apt-get install -y \
        build-essential \
        gdb \
        cmake \
        clang \
        libc6-dev \
        libssl-dev \
        zlib1g-dev \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*


RUN gcc --version && make --version && cmake --version
